# Generated by Django 3.1.3 on 2022-03-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0005_auto_20220322_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
