# Generated by Django 3.1.3 on 2022-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0007_auto_20220323_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='---'),
        ),
    ]
