# Generated by Django 3.2.3 on 2022-04-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0009_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main_app.portfolio')),
            ],
        ),
    ]
